export const LANGUAGES = [
  { code: "hi", label: "हिंदी" },
  { code: "mr", label: "मराठी" },
  { code: "en", label: "English" }
];

export const TRANSLATIONS = {
  mr: {
    'logo-name': 'जय माता दी ज्योतिष',
    'logo-tagline': 'आचार्य रतिश कुमार · वैदिक मार्गदर्शन',
    'header-hours': 'सोम–शनि: सकाळी १०:०० – रात्री ८:००',
    'hero-badge': '✨ आचार्य रतिश कुमार - ऑनलाइन ज्योतिष सेवा',
    'hero-title': 'आपल्या जीवनाचा मार्ग<br>ज्योतिषाने उजळवा',
    'hero-subtitle': 'वैदिक ज्योतिष, कुंडली विश्लेषण आणि आध्यात्मिक मार्गदर्शनाद्वारे तुमच्या जीवनात सुख, समृद्धी आणि शांतता आणा।',
    'hero-btn1': '🧙 ज्योतिषाशी बोला',
    'hero-btn2': '📖 अधिक माहिती',
    stat1: 'वर्षांचा अनुभव',
    stat2: 'समाधानी ग्राहक',
    stat3: 'तज्ज्ञ ज्योतिषी',
    stat4: 'भाषांमध्ये सेवा',
    stat5: 'सरासरी रेटिंग',
    'nav-home': 'मुखपृष्ठ',
    'nav-about': 'आचार्य',
    'nav-blog': 'ब्लॉग',
    'nav-kundali': 'कुंडली विश्लेषण',
    'nav-kaalsarp': 'कालसर्प दोष निवारण',
    'nav-contact': 'संपर्क',
    'nav-services': 'आमच्या सेवा ▾',
    'nav-marriage': 'विवाह कुंडली मिलान',
    'nav-vastu': 'वास्तु शास्त्र परामर्श',
    'nav-career': 'करियर आणि वित्त',
    'nav-gems': 'रत्न सल्ला आणि उपचार',
    'nav-personal': 'व्यक्तिगत मार्गदर्शन',
    'nav-business': 'व्यापार ज्योतिष',
    'nav-education': 'शिक्षण ज्योतिष',
    'nav-health': 'आरोग्य आणि निरोगीपणा',
    'nav-spiritual': 'आध्यात्मिक उपचार',
    'nav-horoscope': 'राशीभविष्य',
    'nav-panchang': 'पंचांग',
    'reviews-title': 'ग्राहकांचे अनुभव',
    'contact-title': 'आमच्याशी संपर्क करा',
    'contact-info-title': 'संपर्क माहिती',
    'form-title': 'ज्योतिष सल्ला मागवा',
    'form-name-label': 'आपले नाव *',
    'form-phone-label': 'फोन नंबर *',
    'form-service-label': 'सेवा निवडा *',
    'form-msg-label': 'संदेश',
    'form-btn': '📨 सल्ला मागवा',
  },
  hi: {
    'logo-name': 'जय माता दी ज्योतिष',
    'logo-tagline': 'आचार्य रतिश कुमार · वैदिक मार्गदर्शन',
    'header-hours': 'सोम–शनि: सुबह १०:०० – रात ८:००',
    'hero-badge': '✨ आचार्य रतिश कुमार - ऑनलाइन ज्योतिष सेवा',
    'hero-title': 'अपने जीवन का मार्ग<br>ज्योतिष से रोशन करें',
    'hero-subtitle': 'वैदिक ज्योतिष, कुंडली विश्लेषण और आध्यात्मिक मार्गदर्शन से अपने जीवन में सुख, समृद्धि और शांति लाएं।',
    'hero-btn1': '🧙 ज्योतिषी से बात करें',
    'hero-btn2': '📖 अधिक जानकारी',
    stat1: 'वर्षों का अनुभव',
    stat2: 'संतुष्ट ग्राहक',
    stat3: 'विशेषज्ञ ज्योतिषी',
    stat4: 'भाषाओं में सेवा',
    stat5: 'औसत रेटिंग',
    'nav-home': 'होम',
    'nav-about': 'आचार्य',
    'nav-blog': 'ब्लॉग',
    'nav-kundali': 'कुंडली विश्लेषण',
    'nav-kaalsarp': 'कालसर्प दोष निवारण',
    'nav-contact': 'संपर्क',
    'nav-services': 'हमारी सेवाएं ▾',
    'nav-marriage': 'विवाह कुंडली मिलान',
    'nav-vastu': 'वास्तु शास्त्र परामर्श',
    'nav-career': 'करियर एवं वित्त',
    'nav-gems': 'रत्न परामर्श एवं उपाय',
    'nav-personal': 'व्यक्तिगत मार्गदर्शन',
    'nav-business': 'व्यापार ज्योतिष',
    'nav-education': 'शिक्षा ज्योतिष',
    'nav-health': 'स्वास्थ्य एवं निरोगी जीवन',
    'nav-spiritual': 'आध्यात्मिक उपचार',
    'nav-horoscope': 'राशिफल',
    'nav-panchang': 'पंचांग',
    'reviews-title': 'ग्राहकों के अनुभव',
    'contact-title': 'हमसे संपर्क करें',
    'contact-info-title': 'संपर्क जानकारी',
    'form-title': 'ज्योतिष परामर्श लें',
    'form-name-label': 'आपका नाम *',
    'form-phone-label': 'फोन नंबर *',
    'form-service-label': 'सेवा चुनें *',
    'form-msg-label': 'संदेश',
    'form-btn': '📨 परामर्श लें',
  },
  en: {
    'logo-name': 'Jai Mata Di Astrology',
    'logo-tagline': 'Acharya Ratish Kumar · Vedic Wisdom',
    'header-hours': 'Mon–Sat: 10:00 AM – 8:00 PM',
    'hero-badge': '✨ Online Vedic Astrology by Acharya Ratish Kumar',
    'hero-title': 'Illuminate Your Path<br>with the Stars',
    'hero-subtitle': 'Through Vedic Astrology, Kundali Analysis, and Spiritual Guidance, bring happiness, prosperity, and peace to your life.',
    'hero-btn1': '🧙 Consult Now',
    'hero-btn2': '📖 Learn More',
    stat1: 'Years of Experience',
    stat2: 'Happy Clients',
    stat3: 'Expert Astrologer',
    stat4: 'Languages Supported',
    stat5: 'Avg Rating',
    'nav-home': 'Home',
    'nav-about': 'The Acharya',
    'nav-blog': 'Blog',
    'nav-kundali': 'Kundali Analysis',
    'nav-kaalsarp': 'Kaal Sarp Dosh',
    'nav-contact': 'Contact',
    'nav-services': 'Our Services ▾',
    'nav-marriage': 'Marriage Matching',
    'nav-vastu': 'Vastu Consultation',
    'nav-career': 'Career & Finance',
    'nav-gems': 'Gemstone Recommendations',
    'nav-personal': 'Personal Guidance',
    'nav-business': 'Business Astrology',
    'nav-education': 'Education Astrology',
    'nav-health': 'Health & Wellness',
    'nav-spiritual': 'Spiritual Healing',
    'nav-horoscope': 'Horoscope',
    'nav-panchang': 'Panchang',
    'reviews-title': 'Client Testimonials',
    'contact-title': 'Contact Us',
    'contact-info-title': 'Contact Information',
    'form-title': 'Get Astrology Advice',
    'form-name-label': 'Your Name *',
    'form-phone-label': 'Phone Number *',
    'form-service-label': 'Select Service *',
    'form-msg-label': 'Message',
    'form-btn': '📨 Request Advice',
  },
};

export const NAV_ITEMS = [
  { key: 'nav-home', to: '/', icon: 'Home' },
  { key: 'nav-about', to: '/about', icon: 'User' },
  { 
    key: 'nav-services', 
    to: '#', 
    icon: 'Star',
    children: [
      { key: 'nav-kundali', to: '/services/kundali-analysis' },
      { key: 'nav-marriage', to: '/services/marriage-matching' },
      { key: 'nav-vastu', to: '/services/vastu-consultation' },
      { key: 'nav-career', to: '/services/career-guidance' },
      { key: 'nav-gems', to: '/services/gemstone-consultation' },
      { key: 'nav-personal', to: '/services/personal-guidance' },
      { key: 'nav-business', to: '/services/business-astrology' },
      { key: 'nav-education', to: '/services/education-astrology' },
      { key: 'nav-health', to: '/contact' },
      { key: 'nav-spiritual', to: '/contact' },
    ]
  },
  { key: 'nav-horoscope', to: '/horoscope', icon: 'Flame' },
  { key: 'nav-panchang', to: '/panchang', icon: 'Sun' },
  { key: 'nav-blog', to: '/blog', icon: 'BookText' },
  { key: 'nav-contact', to: '/contact', icon: 'Phone' },
];

export const RASHI_DATA = [
  { key: 'Mesh', symbol: '♈', name: { mr: 'मेष', hi: 'मेष', en: 'ARIES' }, traits: { mr: 'साहसी, उत्साही आणि आत्मविश्वासू.', hi: 'साहसी, उत्साही और आत्मविश्वासी।', en: 'Bold, ambitious and confident.' }, luckyNumber: 9, luckyColor: { mr: 'लाल', hi: 'लाल', en: 'Red' } },
  { key: 'Vrishabh', symbol: '♉', name: { mr: 'वृषभ', hi: 'वृषभ', en: 'TAURUS' }, traits: { mr: 'संयमी, विश्वासू आणि कष्टाळू.', hi: 'धैर्यवान, विश्वसनीय और मेहनती।', en: 'Strong, dependable and hardworking.' }, luckyNumber: 6, luckyColor: { mr: 'पांढरा', hi: 'सफेद', en: 'White' } },
  { key: 'Mithun', symbol: '♊', name: { mr: 'मिथुन', hi: 'मिथुन', en: 'GEMINI' }, traits: { mr: 'बुद्धिमान, जिज्ञासू आणि बोलका.', hi: 'बुद्धिमान, जिज्ञासु और बातूनी।', en: 'Intellectual, curious and communicative.' }, luckyNumber: 5, luckyColor: { mr: 'हिरवा', hi: 'हरा', en: 'Green' } },
  { key: 'Kark', symbol: '♋', name: { mr: 'कर्क', hi: 'कर्क', en: 'CANCER' }, traits: { mr: 'भावनिक, काळजीवाहू आणि कल्पक.', hi: 'भावुक, देखभाल करने वाला और कल्पनाशील।', en: 'Emotional, nurturing and imaginative.' }, luckyNumber: 2, luckyColor: { mr: 'चंदेरी', hi: 'रजत', en: 'Silver' } },
  { key: 'Singh', symbol: '♌', name: { mr: 'सिंह', hi: 'सिंह', en: 'LEO' }, traits: { mr: 'नेतृत्वक्षम, उदार आणि तेजस्वी.', hi: 'नेतृत्व करने वाला, उदार और तेजस्वी।', en: 'Generous, loyal and charismatic.' }, luckyNumber: 1, luckyColor: { mr: 'सोनेरी', hi: 'सुनहरा', en: 'Gold' } },
  { key: 'Kanya', symbol: '♍', name: { mr: 'कन्या', hi: 'कन्या', en: 'VIRGO' }, traits: { mr: 'व्यवस्थित, चिकित्सक आणि सेवाभावी.', hi: 'व्यवस्थित, विश्लेषणात्मक और सेवाभावी।', en: 'Practical, analytical and helpful.' }, luckyNumber: 5, luckyColor: { mr: 'तपकिरी', hi: 'भूरा', en: 'Brown' } },
  { key: 'Tula', symbol: '♎', name: { mr: 'तुला', hi: 'तुला', en: 'LIBRA' }, traits: { mr: 'न्यायप्रिय, कलाप्रेमी आणि संतुलित.', hi: 'न्यायप्रिय, कलाप्रेमी और संतुलित।', en: 'Diplomatic, artistic and balanced.' }, luckyNumber: 7, luckyColor: { mr: 'गुलाबी', hi: 'गुलाबी', en: 'Pink' } },
  { key: 'Vrishchik', symbol: '♏', name: { mr: 'वृश्चिक', hi: 'वृश्चिक', en: 'SCORPIO' }, traits: { mr: 'रहस्यमयी, प्रबळ इच्छाशक्ती आणि निष्ठावान.', hi: 'रहस्यमयी, मजबूत इच्छाशक्ति और वफादार।', en: 'Mysterious, passionate and loyal.' }, luckyNumber: 9, luckyColor: { mr: 'लाल', hi: 'लाल', en: 'Dark Red' } },
  { key: 'Dhanu', symbol: '♐', name: { mr: 'धनु', hi: 'धनु', en: 'SAGITTARIUS' }, traits: { mr: 'आशावादी, स्पष्टवक्ता आणि धार्मिक.', hi: 'आशावादी, स्पष्टवादी और धार्मिक।', en: 'Optimistic, honest and philosophical.' }, luckyNumber: 3, luckyColor: { mr: 'पिवळा', hi: 'पीला', en: 'Yellow' } },
  { key: 'Makar', symbol: '♑', name: { mr: 'मकर', hi: 'मकर', en: 'CAPRICORN' }, traits: { mr: 'शिस्तप्रिय, महत्त्वाकांक्षी आणि व्यावहारिक.', hi: 'अनुशासित, महत्वाकांक्षी और व्यावहारिक।', en: 'Disciplined, ambitious and practical.' }, luckyNumber: 8, luckyColor: { mr: 'काळा', hi: 'काला', en: 'Black' } },
  { key: 'Kumbh', symbol: '♒', name: { mr: 'कुंभ', hi: 'कुंभ', en: 'AQUARIUS' }, traits: { mr: 'स्वतंत्र विचारसरणी, आधुनिक आणि कल्पक.', hi: 'स्वतंत्र विचारक, आधुनिक और मिलनसार।', en: 'Inventive, unique and progressive.' }, luckyNumber: 8, luckyColor: { mr: 'निळा', hi: 'नीला', en: 'Blue' } },
  { key: 'Meen', symbol: '♓', name: { mr: 'मीन', hi: 'मीन', en: 'PISCES' }, traits: { mr: 'अध्यात्मिक, दयाळू आणि संवेदनशील.', hi: 'आध्यात्मिक, दयालु और संवेदनशील।', en: 'Spiritual, empathetic and wise.' }, luckyNumber: 3, luckyColor: { mr: 'पिवळा', hi: 'पीला', en: 'Pale Yellow' } },
];

export const TICKER_ITEMS = [
  '✨ आचार्य रतिश कुमार से ऑनलाइन परामर्श',
  '🌙 ज्योतिष और वास्तु सलाह अब घर बैठे',
  '🤝 व्यक्तिगत मार्गदर्शन और सटीक उपाय',
  '🪐 जीवन की समस्याओं का वैदिक समाधान',
  '📞 आज ही अपना समय आरक्षित करें',
];

export const DAILY_TIPS = [
  { day: 1, energy: "High", tip: { mr: "आज नवीन कामाची सुरुवात करण्यासाठी दिवस उत्तम आहे.", hi: "आज नए काम की शुरुआत के लिए दिन उत्तम है।", en: "Today is excellent for starting new projects." } },
  { day: 2, energy: "Moderate", tip: { mr: "गुंतवणुकीच्या निर्णयांत सावधगिरी बाळगा.", hi: "निवेश के फैसलों में सावधानी बरतें।", en: "Be cautious with investment decisions today." } },
  { day: 3, energy: "Peaceful", tip: { mr: "आज कुटुंबासोबत वेळ घालवण्यासाठी चांगला काळ आहे.", hi: "आज परिवार के साथ समय बिताने का अच्छा समय है।", en: "Great day for spending time with family." } },
  { day: 4, energy: "Active", tip: { mr: "आरोग्याकडे लक्ष द्या, व्यायामाला प्राधान्य द्या.", hi: "स्वास्थ्य पर ध्यान दें, व्यायाम को प्राथमिकता दें।", en: "Focus on health, prioritize exercise today." } },
  { day: 5, energy: "Productive", tip: { mr: "अडलेली कामे पूर्ण करण्यासाठी आजचा दिवस शुभ आहे.", hi: "रुके हुए कार्यों को पूरा करने के लिए आज का दिन शुभ है।", en: "Auspicious day to complete pending tasks." } },
  { day: 6, energy: "Creative", tip: { mr: "नवीन कल्पनांवर काम करण्यासाठी उत्तम दिवस.", hi: "नए विचारों पर काम करने के लिए बेहतरीन दिन।", en: "Excellent day to work on new creative ideas." } },
  { day: 7, energy: "Spiritual", tip: { mr: "आज ध्यान आणि आध्यात्मिक साधनेसाठी वेळ काढा.", hi: "आज ध्यान और आध्यात्मिक साधना के लिए समय निकालें।", en: "Take time for meditation and spiritual practice today." } },
  { day: 8, energy: "Success", tip: { mr: "महत्वाच्या करारांवर सही करण्यासाठी अनुकूल काळ.", hi: "महत्वपूर्ण अनुबंधों पर हस्ताक्षर करने के लिए अनुकूल समय।", en: "Favorable time for signing important contracts." } },
  { day: 9, energy: "Vibrant", tip: { mr: "सामाजिक कार्यात सहभागी होण्यासाठी चांगला दिवस.", hi: "सामाजिक कार्यों में भाग लेने के लिए अच्छा दिन।", en: "Good day for participating in social activities." } },
  { day: 10, energy: "Careful", tip: { mr: "आज प्रवासात विशेष काळजी घ्यावी.", hi: "आज यात्रा में विशेष सावधानी बरतें।", en: "Take extra care during travel today." } },
  { day: 11, energy: "Prosperity", tip: { mr: "आर्थिक लाभाचे योग जुळून येतील.", hi: "आर्थिक लाभ के योग बनेंगे।", en: "Chances of financial gains are high today." } },
  { day: 12, energy: "Calm", tip: { mr: "मानसिक शांतीसाठी थोडा वेळ एकांत घालवा.", hi: "मानसिक शांति के लिए कुछ समय एकांत में बिताएं।", en: "Spend some time in solitude for mental peace." } },
  { day: 13, energy: "Energetic", tip: { mr: "तुमचा उत्साह आज शिखरावर असेल.", hi: "आपका उत्साह आज चरम पर होगा।", en: "Your enthusiasm will be at its peak today." } },
  { day: 14, energy: "Balance", tip: { mr: "वैयक्तिक आणि व्यावसायिक आयुष्यात ताळमेळ ठेवा.", hi: "व्यक्तिगत और व्यावसायिक जीवन में तालमेल रखें।", en: "Maintain balance between personal and professional life." } },
  { day: 15, energy: "Insightful", tip: { mr: "आज अचानक नवीन मार्ग सापडण्याची शक्यता आहे.", hi: "आज अचानक नया रास्ता मिलने की संभावना है।", en: "Insightful day with chances of finding new paths." } },
  { day: 16, energy: "Social", tip: { mr: "मित्रमैत्रिणींच्या गाठीभेटीतून आनंद मिळेल.", hi: "दोस्तों से मिलने से खुशी मिलेगी।", en: "Joy in meeting friends and relatives today." } },
  { day: 17, energy: "Stable", tip: { mr: "आजचा दिवस स्थिर आणि समाधानकारक असेल.", hi: "आज का दिन स्थिर और संतोषजनक रहेगा।", en: "Day will be stable and satisfying." } },
  { day: 18, energy: "Growth", tip: { mr: "उत्पन्नाचे अकल्पित स्रोत निर्माण होऊ शकतात.", hi: "आय के अप्रत्याशित स्रोत बन सकते हैं।", en: "Unexpected sources of income may arise today." } },
  { day: 19, energy: "Focus", tip: { mr: "कामात एकाग्रता ठेवून मोठे यश मिळवाल.", hi: "काम में एकाग्रता रखकर बड़ी सफलता पाएंगे।", en: "Achieve great success through focused work." } },
  { day: 20, energy: "Lucky", tip: { mr: "अनपेक्षित आनंदाची बातमी मिळेल.", hi: "अचानक कोई शुभ समाचार मिलेगा।", en: "Expect some unexpected good news today." } },
  { day: 21, energy: "Strong", tip: { mr: "आत्मविश्वास वाढवणारा दिवस.", hi: "आत्मविश्वास बढ़ाने वाला दिन।", en: "A day that boosts your self-confidence." } },
  { day: 22, energy: "Wisdom", tip: { mr: "वडिलधाऱ्यांचा सल्ला मोलाचा ठरेल.", hi: "बड़ों की सलाह कीमती साबित होगी।", en: "Advice from elders will be very valuable today." } },
  { day: 23, energy: "Joy", tip: { mr: "मन प्रसन्न राहील अशा गोष्टी करा.", hi: "ऐसी चीजें करें जिनसे मन प्रसन्न रहे।", en: "Do things that keep your mind happy today." } },
  { day: 24, energy: "Ambitious", tip: { mr: "मोठी ध्येये ठेवण्यासाठी आजचा दिवस उत्तम.", hi: "बड़े लक्ष्य रखने के लिए आज का दिन उत्तम है।", en: "Excellent day to set ambitious goals." } },
  { day: 25, energy: "Healing", tip: { mr: "आज स्वतःच्या मनावर आणि शरीरावर लक्ष द्या.", hi: "आज अपने मन और शरीर पर ध्यान दें।", en: "Focus on healing your mind and body today." } },
  { day: 26, energy: "Connection", tip: { mr: "जुन्या मित्रांशी संपर्क साधण्यासाठी चांगला काळ.", hi: "पुराने दोस्तों से संपर्क करने का अच्छा समय है।", en: "Good time to reconnect with old friends." } },
  { day: 27, energy: "Reflective", tip: { mr: "भूतकाळातील चुका सुधारण्याची संधी मिळेल.", hi: "बीते हुए समय की गलतियों को सुधारने का मौका मिलेगा।", en: "Opportunity to correct past mistakes today." } },
  { day: 28, energy: "Advance", tip: { mr: "करियरमध्ये एखादे पाऊल पुढे टाकाल.", hi: "करियर में एक कदम आगे बढ़ाएंगे।", en: "Make progress in your career today." } },
  { day: 29, energy: "Charity", tip: { mr: "आज गरजू व्यक्तीला मदत करणे शुभ ठरेल.", hi: "आज किसी जरूरतमंद की मदद करना शुभ होगा।", en: "Helping someone in need will be auspicious today." } },
  { day: 30, energy: "Accomplish", tip: { mr: "महिनाभरातील सर्व उद्दिष्टे साध्य करण्याचा दिवस.", hi: "महीने के सभी लक्ष्यों को प्राप्त करने का दिन।", en: "Day to accomplish all your monthly goals." } },
  { day: 31, energy: "Gratitude", tip: { mr: "आजच्या दिवसाची सांगता कृतज्ञतेने करा.", hi: "आज के दिन का समापन कृतज्ञता के साथ करें।", en: "End the day with a sense of gratitude." } }
];
